### ISSUE TITLE
Fix github links in website landing page

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows-samples#102]
We should remove the global "Star" on the website that points to the react-native-windows repo and instead move it down to the "Get started with Windows" section and add a similar one for Mac to ensure we are pointing people to the right repos for the two implementations. 

We should also remove the "Github" tab in the top header as well - instead add a page in the resources section that consolidates all the githubs that are part of the RN at MSFT family of offerings.

**Comment by chrisglein** [comment]
This thing:

![image](https://user-images.githubusercontent.com/26607885/81973083-78c6f200-95d8-11ea-865d-2411cab237fd.png)

We need Windows AND macOS there

**Comment by kikisaints** [comment]
do we have a macos twitter handle for this?

**Comment by harinikmsft** [comment]
No - our twitter handle is common for all React Native things. So, the github at the top shouldnt be there. Instead make 2 "Star" buttons - one for Windows and one for Mac and them to the "Build for Windows" and "Build for Mac" sections below.
