### ISSUE TITLE
Ensure release notes for 0.63 mention breaking change in template

### ISSUE THREAD

**Issue by dannyvv** [microsoft/react-native-windows-samples#133]
At the time of writing we don't have an upgrade tool for templates yet.
PR [5091](https://github.com/microsoft/react-native-windows/pull/5091) in the react-native-windows repo introduces a breaking change for which users with C# projects and are recommended to update their solution and one C# file. 
If users upgrade from 0.61 or a prerelease of 0.62 they might also need to do some more changes to the .csproj file as well.

For now these changes are documented in an [.md file](https://github.com/microsoft/react-native-windows/blob/2c6a912445b87ed718e328add7276bf7fc1b5cdb/docs/breakingchanges-0.63.md) in the code repo that was checked in as part of the breaking change.

This issue is to track we document for users (or hopefully have had time to implement upgrade tooling so users don't have to worry...)

**Comment by NickGerleman** [comment]
I think for this one we decided to tell people to just Regen the project since there were too many breaking changes? Any action items here?
