### ISSUE TITLE
Issue with navigator and windows version in react-native

### ISSUE THREAD

**Issue by willerpp** [microsoft/react-native-windows-samples#150]
Hi Guys I'm using the windows plugin in my react-native project, I only have in my project a navigator with 4 pages empty, I have tested this navigator in an android emulator and it worked perfectly but after I applied these commands :

npm install --save-dev rnpm-plugin-windows
react-native windows
react-native run-windows 

I received in the windows version of the project this error message 👍 
**TypeError: Cannot read property 'Direction' of undefined**

I'm using React Navigation V5 with react-native-gesture-handler.
Any help will be appreciate.
thank you

**Comment by harinikmsft** [comment]
Hello! 

Thanks for trying this out. `react-navigation` module is not supported in Windows yet. See [Issue 3884](https://github.com/microsoft/react-native-windows/issues/3884) in the main repo where this is being discussed. We are working on it right now and hope to have it really soon! 

I am closing this issue so we can continue the conversation in the main repo where the implementation occurs.

Thanks!
