### ISSUE TITLE
support for keyboard events???

### ISSUE THREAD

**Issue by willerpp** [microsoft/react-native-windows-samples#154]
Hi guys, i need to have hot keys in my react native windows desktop, there is a way to know what keyboard combination was pressed by the user? and trigger a button click?
thank you

**Comment by chrisglein** [comment]
@harinikmsft is in the process of documenting the keyboard story. Assigning to her for followup.

**Comment by harinikmsft** [comment]
Hello @willerpp - please take a look at this [PR](https://github.com/microsoft/react-native-windows/pull/5590) that documents some of the APIs that you can use to accomplish what you are looking for. We will be adding documentation here in the website soon, but for now this should help unblock you.
