### ISSUE TITLE
Can't build Native UI Module following docs: native-modules-setup and view-managers

### ISSUE THREAD

**Issue by mjfusa** [microsoft/react-native-windows-samples#157]
Doc references: https://microsoft.github.io/react-native-windows/docs/native-modules-setup
Doc references: https://microsoft.github.io/react-native-windows/docs/view-managers

RNW 0.62.  I've created a native UI module in C++ in a separate project in the same solution as my main RNW app project. It all builds fine except I'm getting MDMERGE errors.  I get 63 variants of this:
```
Severity    Code    Description Project File    Line    Suppression State
Error   MDM2009 Duplicate type Microsoft.ReactNative.AccessibilityAction found processing metadata file C:\rnww\rnwo\windows\x64\Debug\NativeUICtrl\Microsoft.ReactNative.winmd, type already exists in file C:\rnww\rnwo\node_modules\react-native-windows\Microsoft.ReactNative\target\x64\Debug\Microsoft.ReactNative\Microsoft.ReactNative.winmd.   myrnProject C:\rnww\rnwo\windows\myrnProject\MDMERGE    1
```
This sample [SampleApp](https://github.com/microsoft/react-native-windows/tree/master/packages/microsoft-reactnative-sampleapps) contains a custom control and works as expected - but it is part of the main RNW repo. This sample can't be easily reproduced without the repo as it makes references to node_modules in a private 'vnext' folder. For example in ```SampleApp.sln``` there are several references like this: ```Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "Folly", "..\..\..\vnext\Folly\Folly.vcxproj", "{A990658C-CE31-4BCC-976F-0FC6B1AF693D}"```

I eventually got this working (no mdmerge errors!) by comparing my project to ```SampleLibrary.vcxprj``` to ```SampleLibraryCPP.vcxprj``` (Native UI module ins SampleApp), and found the following differences:

```Here are the differences in the Imports between the projects:
**OLD IMPORTS (Removed):**
    <ProjectReference Include="..\..\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj">
      <Project>{f7d32bd0-2749-483e-9a0d-1635ef7e3136}</Project>
      <Private>false</Private>
    </ProjectReference>
  <ImportGroup Label="Shared">
    <Import Project="..\..\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\Microsoft.ReactNative.Cxx.vcxitems" Label="Shared" />
  </ImportGroup>
___
**NEW IMPORTS (Added):**
  <!-- From sample https://github.com/microsoft/react-native-windows/blob/master/packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleLibraryCPP.vcxproj -->
  <ImportGroup Label="ReactNativeWindowsTargets">
    <Import Project="$(ReactNativeWindowsDir)\PropertySheets\External\Microsoft.ReactNative.Uwp.CppLib.targets" Condition="Exists('$(ReactNativeWindowsDir)\PropertySheets\External\Microsoft.ReactNative.Uwp.CppLib.targets')" />
  </ImportGroup>
  <Target Name="EnsureReactNativeWindowsTargets" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references targets in your node_modules\react-native-windows folder. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('$(ReactNativeWindowsDir)\PropertySheets\External\Microsoft.ReactNative.Uwp.CppLib.props')" Text="$([System.String]::Format('$(ErrorText)', '$(ReactNativeWindowsDir)\PropertySheets\External\Microsoft.ReactNative.Uwp.CppLib.props'))" />
    <Error Condition="!Exists('$(ReactNativeWindowsDir)\PropertySheets\External\Microsoft.ReactNative.Uwp.CppLib.targets')" Text="$([System.String]::Format('$(ErrorText)', '$(ReactNativeWindowsDir)\PropertySheets\External\Microsoft.ReactNative.Uwp.CppLib.targets'))" />
  </Target>
```
Please advise on next steps here as it seems these project settings are not accessible via Project Settings and must be entered by editing the vcxproj file. Should the docs include the instructions for manually updating the .vcxproj file?

BTW: There are open issues for creating C++ and C# native modules using the CLI:  https://github.com/microsoft/react-native-windows/issues/3203 https://github.com/microsoft/react-native-windows/issues/3201

Doc references: https://microsoft.github.io/react-native-windows/docs/native-modules-setup
Doc references: https://microsoft.github.io/react-native-windows/docs/view-managers

**Comment by mjfusa** [comment]
Admin: Can you please create a label: `AppConsult`.

**Comment by jonthysell** [comment]
Did you follow *all* of the instructions here? https://microsoft.github.io/react-native-windows/docs/native-modules-setup#referencing-react-native-windows-in-your-project

From [Referencing React Native Windows in your Project](https://microsoft.github.io/react-native-windows/docs/native-modules-setup#referencing-react-native-windows-in-your-project):

> After you've added the reference, you need to make sure it doesn't copy itself into your build (otherwise it'll cause build conflicts down the line when you're trying on consume your library):
> 
> 1. Open the Solution Explorer sidebar.
> 1. Under your `MyLibrary` project, expand the `References`.
> 1. Right-click on `Microsoft.ReactNative`.
> 1. Select `Properties`.
> 1. Under `Build`, Change `Copy Local` to `False`.

This should fix the mdmerge build conflicts. Since you've already built it once without that set, you may need to run clean solution first to get rid of those conflicting files. And if clean solution doesn't work, you may need to delete the bin/obj folders manually.
