### ISSUE TITLE
Update AppTheme guidance doc to point to Appearance module instead

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows-samples#167]
The top section of this guidance doc needs to be updated : https://microsoft.github.io/react-native-windows/docs/windowsbrush-and-theme

[AppTheme](https://microsoft.github.io/react-native-windows/docs/apptheme-api) was deprecated in Windows to use [Appearance](https://reactnative.dev/docs/appearance) module instead.

**Comment by chrisglein** [comment]
See issue on main repo for AppTheme/Appearance reconciliation: https://github.com/microsoft/react-native-windows/issues/3701
