### ISSUE TITLE
Native modules docs reference 0.61 (& other issues)

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows-samples#182]
I recently was helping an external developer (#4516) who was trying to use a native module they had written in C#. This developer is a self-described JS dev, never before used C#, Visual Studio, UWP, or anything like that.
They hit lots of bumps on the road and ended up kind of giving up (and instead re-wrote their code as C++), so I wanted to capture things here and gather ideas on how we can improve this for others:

- The native module docs have samples but [they are for RNW 0.61](https://github.com/microsoft/react-native-windows-samples/blob/master/samples/NativeModuleSample/README.md)
- The RNW NM docs talk about Xcode and Android studio, and not about Visual Studio or Windows at all. This is pretty confusing:
  - [C++ sample readme](https://github.com/microsoft/react-native-windows-samples/blob/master/samples/NativeModuleSample/cppwinrt/README.md)
  - [C# sample readme](https://github.com/microsoft/react-native-windows-samples/blob/master/samples/NativeModuleSample/csharp/README.md)
- The app project didn't pass WACK because of V8jsi - it looks like they were using RNW 0.61, which still suffers from the "v8jsi.dll always gets linked in" problem - likely because the samples use 61 too.
- The native module in C# cannot be used in an app that wants to pass WACK as you can't just load the CLR in a store app and you need the trick I described in my [WinRTComponent project](http://github.com/asklar/WinRTComponent) or set the min platform to 15063 or lower (but that part won't work with RNW's usage of XAML APIs).

**Comment by stmoy** [comment]
@jonthysell - I see a bunch of changes that you've made over the last couple of days here, can we close this issue?

**Comment by stmoy** [comment]
Alex to doublecheck what is still out of date now that Jon has updated a bunch of stuff.
