### ISSUE TITLE
Rename repository, update readme, to reflect that this repository also relates to RN macOS implementation 

### ISSUE THREAD

**Issue by Simek** [microsoft/react-native-windows-samples#190]
Currently the name `react-native-windows-samples` do not suggest that this repository is related too to the RN macOS and contains the website for two RN platforms from Microsoft.

> This repository is a companion to the React Native for Windows repo and features sample React Native apps, components, and templates. [...]

The same problem is with the Readme file which do not mention macOS anywhere nor website source.

Repository description is also inaccurate:
<img width="244" src="https://user-images.githubusercontent.com/719641/90335065-43181780-dfd2-11ea-8de8-b14cd5a0d733.png">

**Comment by chrisglein** [comment]
This repro predated much of the macOS additions and we haven't renamed the repo, but we should. Using "desktop" kind of works, but doesn't capture the non-desktopy targets that RNW enables like Xbox and HoloLens. So yes agree to rename, we need to pick the right one. Maybe `microsoft\react-native-samples` is okay.

The readme should definitely cover more on macOS.

**Comment by Simek** [comment]
Also the website URL should be updated: https://microsoft.github.io/react-native-windows/

**Comment by Simek** [comment]
And what do you think about changing the prefix of the macOS related pages from (quite enigmatic at the first glace) `rnm-` to just `macos-`? Example: https://microsoft.github.io/react-native-windows/docs/rnm-getting-started

**Comment by kikisaints** [comment]
Created a PR to address the readme... however I don't have write access to the repo description :( 
@asklar is that something you have the ability to do?

**Comment by asklar** [comment]
@kikisaints I think so - what should it say?

**Comment by kikisaints** [comment]
@asklar how does this sound?:

> A repository showcasing React Native samples and templates for Windows, macOS, and Duo.

**Comment by asklar** [comment]
Sounds good @kikisaints - just to confirm do we want to say Duo or Surface Duo?

**Comment by kikisaints** [comment]
Ah! Good catch, should be Surface Duo.

**Comment by asklar** [comment]
@kikisaints Done!

**Comment by Simek** [comment]
@kikisaints What about the repository name and website URL?

**Comment by asklar** [comment]
that might be a little trickier. there are pieces of the samples repo that rely on the react-native-windows repo being a prefix of this repo's name (see siteconfig.js here)
