### ISSUE TITLE
Include general C#/C++ developer documentation, clean up Native UI Components docs

### ISSUE THREAD

**Issue by giregk** [microsoft/react-native-windows-samples#193]
# Proposal: Improve the documentation about writing Native modules and Native UI modules

- The code on [Native UI Components](https://microsoft.github.io/react-native-windows/docs/view-managers) is clearly a bad copy-paste and is broken => this should be fixed
- The pages [Native Modules](https://microsoft.github.io/react-native-windows/docs/native-modules) and [Native UI Components](https://microsoft.github.io/react-native-windows/docs/view-managers) should link to the github sample pages
- What each part of the code does should be documented because it is currently not understandable for C# and C++ beginners like I am.

**Comment by asklar** [comment]
@giregk I made some updates, could you take a look and see if those help? Would love to hear if there are more improvements we can make or what we can clarify.

**Comment by chrisglein** [comment]
Somewhat related to #62 in that we could benefit from having some general purpose resource links to guide people new to UWP development.

**Comment by giregk** [comment]
@asklar I read the whole documentation. It seems much better than the last time I read it. I saw answers to several questions I once had (such as handling asynchronous tasks in C++/winrt with which I struggled a lot). Thank you very much !

**Comment by stmoy** [comment]
Thank you for following up @giregk - please reach out again if you need any more info!
