### ISSUE TITLE
Update WinUI3 Docs for 0.63

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows-samples#199]
See https://microsoft.github.io/react-native-windows/docs/next/winui3

Needs updating:
- Canary builds no longer needed
- NPM Package section (meant to be NuGet package?)

![image](https://user-images.githubusercontent.com/835219/91029456-a21df380-e5b3-11ea-8a32-9b9025fc956e.png)

**Comment by NickGerleman** [comment]
@stmoy and @acoates-ms: Possibly wanting to set expectations for stability in the doc

**Comment by asklar** [comment]
I think we still want to point people to the canary build since we'll want instructions to work w/the next winui preview. 
WRT the npm package agree we can get rid of that or replace w/nuget

**Comment by stmoy** [comment]
I think the more meta point was "this is in the Windows Basics" section which doesn't seem right. This doesn't seem like a "golden path" scenario yet, so maybe a warning at the top that says "this isn't totally solid" and moving it to an advanced section helps send the right message.

**Comment by harinikmsft** [comment]
@kikisaints has introduced an "experimental" sidebar and moved this WinUI 3 doc into that in this [PR
](https://github.com/microsoft/react-native-windows-samples/pull/211)

Is that all this issue is tracking?

**Comment by NickGerleman** [comment]
The other bit I was concerned about was pushing folks towards canary builds instead of what we have in 0.63. They're pretty rough in ways customers might not expect. E.g. they block usage of community modules, force an unreleased version of React Native to be used, can have breaking changes every build, are often broken, etc). If we really want to push people to use them to get newer WinUI bits than what's in 0.63, that's okay, but I don't think it will be a good experience.

There was I think just a typo in NuGet vs NPM in one place.

**Comment by asklar** [comment]
re: community modules - today no native community modules will work with a winui 3-built microsoft.reactnative.dll. So I think keeping folks on canary helps send the message that this is experimental and set expectations accordingly.
