### ISSUE TITLE
Update supported community modules

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows-samples#202]
E.g. we support datetimepicker. Need to update our docs.

![image](https://user-images.githubusercontent.com/835219/91030780-8b2bd100-e5b4-11ea-86a4-7b7602ce2826.png)

**Comment by rectified95** [comment]
Checkbox is also in, Slider has been long pending maintainers' merge

**Comment by harinikmsft** [comment]
@stmoy has an open PR on this - [PR](https://github.com/microsoft/react-native-windows-samples/pull/197)

**Comment by rectified95** [comment]
Slider just got in as well. @stmoy

**Comment by NickGerleman** [comment]
Reassigning since stmoy is already working on this
