### ISSUE TITLE
Inconsistent Syntax Highlighting For Commands

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows-samples#235]
We see a bunch of examples for commands that get colors at relatively arbitrary points. Seems like we're trying to interpret the Snippet as a programming language instead of a command or raw text?

 E.g. 
![image](https://user-images.githubusercontent.com/835219/92002666-f4b68880-ecf4-11ea-8692-273cc877fc49.png)

**Comment by jonthysell** [comment]
When you use the ``` markdown tags, you should specify the language so the correct highlighting is applied (the auto-detect isn't perfect). Use `cmd` for command-line commands, ie:

> \```cmd
> echo Hello World
>  \```

outputs 

```cmd
echo Hello World
```

Using

> \```
> echo Hello World
>  \```

outputs

```
echo Hello World
```

**Comment by chrisglein** [comment]
Okay, sounds like we just need to scrub the docs and add language specifiers in the right places. Tagged as "good first issue".

**Comment by chrisglein** [comment]
@chiaramooney Have you covered all the pages at this point? If your done passing over these, with your merged PR I think you can close this.

**Comment by chiaramooney** [comment]
All pages covered.
