### ISSUE TITLE
Website does not render properly on IE...

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows-samples#246]
...3.01a. On a Power Macintosh 8600/200 running Mac OS 8.1. 😜

![image](https://user-images.githubusercontent.com/10852185/92337787-c7553c00-f060-11ea-83fc-d6f2cfcb95db.png)

**Comment by chrisglein** [comment]
That is.. majestic.
But I think we can safely declare that out of our support window 😂
