### ISSUE TITLE
Update Native Modules + Visual Studio documentation

### ISSUE THREAD

**Issue by bzoz** [microsoft/react-native-windows-samples#249]
While trying to port [react-native-config](https://github.com/luggit/react-native-config) I've followed the new 0.63 module guide, and encountered some issues:

- In [Adding React Native Windows to the Visual Studio Solution](https://microsoft.github.io/react-native-windows/docs/native-modules-setup#adding-react-native-windows-to-the-visual-studio-solution): there are no `Microsoft.ReactNative.SharedManaged\Microsoft.ReactNative.SharedManaged.shproj` nor `ReactWindowsCore\ReactWindowsCore.vcxproj` in the `node_modules\react-native-windows` folder. The module builds and works without those though.
- Adding `Microsoft.ReactNative.Cxx` as a reference in the `Shared Projects` only works after reloading the solution. Before that, no such project is present in that tab.
- First build will fail with missing Folly headers, subsequent builds works.
- When adding the module (by using `npm i ..\the_module`) to a RNW app (created by following the guide) the app will fail to build if `node_modules` folder is present in the module folder.
- Running the RNW app with `npx react-native run-windows` fails with:
```
Failed to deploy:     11>C:\[app folder]\node_modules\react-native-config\windows\RNCConfig\RNCConfig.vcxproj : error MSB4057: The target "Deploy" does not exist in the project.
```
(RNCConfig.vcxproj is the module .vcxproj file)
The RN server will start, and the app when started from Visual Studio will connect to that server and work correctly.

**Comment by chrisglein** [comment]
@stmoy For you to collate alongside the other native module documentation feedback.

**Comment by stmoy** [comment]
The steps in this doc should actually get automated by the CLI. When they are, we can remove this page.

**Comment by asklar** [comment]
Similar feedback to what I filed here: microsoft/react-native-windows#5914
