### ISSUE TITLE
Update package.json guidance for native modules

### ISSUE THREAD

**Issue by stmoy** [microsoft/react-native-windows-samples#253]
https://microsoft.github.io/react-native-windows/docs/native-modules-setup#updating-your-packagejson

```
yarn add react-native@0.63 --dev
yarn add react-native-windows@0.63 --peer
```

Depending on which versions of iOS and Android the module supports, this guidance potentially breaks the module when Windows support is added. 

What is the guidance around adding Windows support to a module without breaking iOS and Android?

**Comment by jonthysell** [comment]
Here's what I wrote for react-native-camera, where they target 59 and they don't want to add rnw to their package.json: https://github.com/jonthysell/react-native-camera/blob/master/windows/README.md#local-development-setup-rnw--062
