### ISSUE TITLE
Document all annotations and APIs for Native Modules

### ISSUE THREAD

**Issue by stmoy** [microsoft/react-native-windows-samples#254]
@vmoroz indicated that not all annotations are listed in these tables:
- https://microsoft.github.io/react-native-windows/docs/native-modules#attributes
- https://microsoft.github.io/react-native-windows/docs/native-modules#attributes-1

We should make sure that the docs are up-to-date.

**Comment by asklar** [comment]
@stmoy I think this bug should be about the annotations/macros and not the yarn versioning, please double check me :)

**Comment by stmoy** [comment]
@asklar - correct, my bad. I updated my original issue with the correct links.

**Comment by stmoy** [comment]
Would it be useful to separate the API docs vs. the guidance docs for attributes? Maybe each attribute could have its own page. 

Smallest thing would be to add the missing attributes REACT_INIT and REACT_FUNCTION.

**Comment by asklar** [comment]
This should also speak about the differences and limitations between REACT_METHOD and REACT_SYNC_METHOD

**Comment by asklar** [comment]
Needs documentation for C++ REACT_INIT
