### ISSUE TITLE
c# c++ interop conflict with Microsoft.ReactNative.Managed

### ISSUE THREAD

**Issue by elcssmouhsine** [microsoft/react-native-windows-samples#259]
Using React-Native 0.63.2

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error | NU1201 | Project Microsoft.ReactNative.Managed is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-arm-aot. Project Microsoft.ReactNative.Managed supports: uap10.0.16299 (UAP,Version=v10.0.16299) | Camera | C:\Users\elcss\Documents\examappnative\windows\Camera\Camera.csproj | 1 |

**Comment by jonthysell** [comment]
Please update your project's min version to 16299.

https://microsoft.github.io/react-native-windows/docs/win10-compat
