### ISSUE TITLE
Expand the sample to show parameters/return types that are JSON

### ISSUE THREAD

**Issue by gillpeacegood** [microsoft/react-native-windows-samples#26]
I'ld find it really useful if you were able expand the sample modules to give examples of parameters and return types that are JSON. Eg in FancyMath maybe a complex.

At the moment in my code I'm using JSValue. I suppose that is the best way?

**Comment by stmoy** [comment]
CC: @jonthysell 

JSValue value is the interface that is used to pass around generic JSON objects that aren't strongly typed.

**Comment by gillpeacegood** [comment]
Yeah I agree its the right call but to help other people not have to spend the amount of time I've spent looking for code samples and then at code itself would be useful to have a few examples

**Comment by jonthysell** [comment]
I can look into writing some examples, but in the meantime, here are the unit tests:

https://github.com/microsoft/react-native-windows/blob/master/vnext/Microsoft.ReactNative.Cxx.UnitTests/JSValueTest.cpp

https://github.com/microsoft/react-native-windows/blob/master/vnext/Microsoft.ReactNative.Managed.UnitTests/JSValueTest.cs

**Comment by jonthysell** [comment]
Please see https://microsoft.github.io/react-native-windows/docs/native-modules-jsvalue and the new DataMarshallingExample modules in https://github.com/microsoft/react-native-windows-samples/tree/master/samples/NativeModuleSample
