### ISSUE TITLE
None of the Samples are not working 

### ISSUE THREAD

**Issue by manohargss** [microsoft/react-native-windows-samples#260]
I cloned the samples and trying to open them but none of them open with vs 2019. Is there any pre-requisite to build the projects?

**Comment by chrisglein** [comment]
Which samples did you try and what steps did you follow? Cloning and opening up in VS 2019 isn't going to be sufficient, as there are other dependencies you'll need via NPM. For example look at the [Calculator readme](https://github.com/chrisglein/react-native-windows-samples/tree/master/samples/Calculator) which tells you what steps to follow.

**Comment by manohargss** [comment]
I did not know that some pre-requisites are needed to be done. You can close this issue.
