### ISSUE TITLE
TodosFeed Sample not Building

### ISSUE THREAD

**Issue by manohargss** [microsoft/react-native-windows-samples#263]
I got the code from Git Yesterday and after running the pre-requisites observed that TodosFeed sample is not building.

**Comment by chrisglein** [comment]
> I got the code from Git Yesterday and after running the pre-requisites observed that TodosFeed sample is not building.

Can you be more specific about which steps you were trying and where the first failure occurred?

I think there are some problems in the steps in the [TodosFeed readme](https://github.com/microsoft/react-native-windows-samples/tree/master/samples/TodosFeed) but it'd be helpful to know what _you_ hit.

The steps say:
`react-native run-windows`
Which assumes a global install of the react-native command, which we don't recommend in current versions of RNW but did at the time this sample was written (it targets an older version).

The steps also say:
`yarn start`
Which 1) says to run from the `TodosFeed` folder but it means specifically `react-native-windows-samples\samples\TodosFeed\TodosFeed`, not `react-native-windows-samples\samples\TodosFeed`, which caught me the first time.

But then again, it assumes a global install of react-native:
```
> yarn start
yarn run v1.17.3
$ react-native start
'react-native' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Overall, this sample targets RN 0.61.5 and hasn't had its steps updated to match the current version. I believe the reason it lagged behind was to wait for the matching macOS update, but macOS has RN 0.62 so at least the sample should be able to updated to that.

**Comment by chrisglein** [comment]
@qmatteoq I remember you mentioning you were maybe going to upgrade this? Seems like it should be clear to move to 0.62 which should address these issues.

**Comment by qmatteoq** [comment]
> @qmatteoq I remember you mentioning you were maybe going to upgrade this? Seems like it should be clear to move to 0.62 which should address these issues.

Yes it's in my to do list 😊 these weeks I'm busy because of Ignite, but as soon as it's done I will work on this. Thanks for your patience!

**Comment by NickGerleman** [comment]
@manohargss I know this is a while later, but please let us know if you're still seeing issues :)
