### ISSUE TITLE
Rationalize public win32/island support

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows-samples#267]
It's apparent a lot of indie devs don't really understand uwp or how RNW apps that are created by our CLI might be different than win32 apps. In some cases this puts a damper on what things they might be able to do (e.g. spawn some other exe, etc.)
A number of 1st and 3rd party partners are already using RNW in a win32 app via xaml islands. The proposal here is to document and rationalize what the right way/supported way of doing this is and to try to encapsulate OS xaml island API usage as much as possible to prevent devs falling into pits

**Comment by asklar** [comment]
We've already talked about this publicly, so we should either retract or document:

- https://youtu.be/TZnajQqqKV8?t=1925
- https://youtu.be/Ga8oW0VUo2M?t=243
- https://github.com/microsoft/react-native-windows-samples/blob/master/samples/TodosFeed/README.md

**Comment by chrisglein** [comment]
Goal is to highlight golden path and very clearly identify the gaps in any other path. Whatever doc we provide here needs to cover this.

**Comment by asklar** [comment]
Described what RNW apps are (UWP) and tradeoffs in https://github.com/microsoft/react-native-windows-samples/pull/270
