### ISSUE TITLE
overwriting the metro.js file for Windows causes Android + iOS to not work

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows-samples#277]
### Environment

This works for any environment, as this is the current state of affairs in order to install, build, and run a React Native Windows application.

### Steps to Reproduce

(Write your steps here:)

1. `npx react-native init <project name> --version ^0.61.5`
2. `cd <project name>`
3. `npx react-native-windows-init`

>At step three, you will be asked to overwrite the metro.js bundler. It is at this point that if the user does so they will break android and ios builds.

### Expected Behavior

that we use a metro bundler that co-exists nicely with android + ios as well.

**Comment by NickGerleman** [comment]
This should be fixed now. Will also update docs.
