### ISSUE TITLE
Not found error while trying to follow the getting started guide

### ISSUE THREAD

**Issue by japf** [microsoft/react-native-windows-samples#28]
I'm getting a "not found" error while following the getting started guide:

```
⨯ ~\source\repos\react-native-sandbox                                                                                                                               
❯ react-native init hello --version ^0.60.0
This will walk you through creating a new React Native project in C:\Users\xxx\source\repos\react-native-sandbox\hello
Using yarn v1.22.0
Installing ^0.60.0...
yarn add v1.22.0
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/0.60.0: Not found".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\jealles\\source\\repos\\react-native-sandbox\\hello3\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Command failed: yarn add ^0.60.0 --exact
```

Changing the version parameter to `--version ^react-native@0.60.0` does work. 
I'm not sure if this is the correct version, I created a PR if that's the case to change the docs.

cc @stmoy

**Comment by japf** [comment]
Might be related to https://github.com/microsoft/react-native-windows-samples/issues/25

**Comment by chrisglein** [comment]
> Might be related to #25

@japf Is it safe to assume then that you used npx to install the CLI instead of doing it globally?

**Comment by japf** [comment]
No, I didn't use npx. I followed exactly the doc, which states:

> Install React Native
> `npm install -g react-native-cli`

[here](https://microsoft.github.io/react-native-windows/docs/getting-started#install-react-native)

**Comment by acoates-ms** [comment]
Looks like the react-native CLI doesn't do the right thing here:
https://github.com/react-native-community/cli/issues/1039

**Comment by harinikmsft** [comment]
We have updated the docs to use npx instead as that is the more updated workflow.
