### ISSUE TITLE
Where to add samples for the Popup component?

### ISSUE THREAD

**Issue by japf** [microsoft/react-native-windows-samples#29]
I'm looking for a sample using the Popup component. It doesn't seem to exist as of now. What would be a good sample project to demonstrate the use of this component ?

Happy to submit a PR for this.

**Comment by chrisglein** [comment]
Old issue, but let me try to catch up with info on the latest:
Documentation for `Popup` is [here](https://microsoft.github.io/react-native-windows/docs/popup-component). There are usage examples via the tests on the main RNW repo [here](https://github.com/microsoft/react-native-windows/blob/6c871e6ba27888804c776e5deeefbc7064e181d0/packages/%40react-native-windows/tester/src/js/examples-win/Popup/PopupExample.windows.tsx). But there isn't a good sample on this repo, which is a fair ask. Using this issue to track that ask.

**Comment by TatianaKapos** [comment]
It looks like issue was created before react-native-gallery which has a page with examples of Popup. Wondering if that's a suitable solution to this instead of creating a new sample project to focus on just one component? @chrisglein

**Comment by chrisglein** [comment]
> It looks like issue was created before react-native-gallery which has a page with examples of Popup. Wondering if that's a suitable solution to this instead of creating a new sample project to focus on just one component? @chrisglein Chris Glein FTE

Good point. If we have a solid sample of `Popup` in the Gallery app, then I don't think we need a separate one. Maybe the work here is to add a link from the [Popup API documentation](https://microsoft.github.io/react-native-windows/docs/popup-component) to the gallery sample?

I don't think we have "deep linking" support (the ability for an app to be launched not to its normal home page but some subpage within the app) built for RN Gallery, but that'd be a great feature to help support this sort of scenario (@chiaramooney  any thoughts on that?). But for the purposes of this a link to the app and/or the sample source on the repo would suffice.
