### ISSUE TITLE
Sqlite database example

### ISSUE THREAD

**Issue by aberba** [microsoft/react-native-windows-samples#297]
The SQLite package at https://github.com/andpor/react-native-sqlite-storage is said to support React Native Windows. Can you guys please do an example of that? Also would be useful to know how to publish such an app as a MISX package. 

I have a template RNW project at https://github.com/aberba/rnw-template but installing the https://github.com/andpor/react-native-sqlite-storage package doesn't work...I believe it needs some native tweaks to get it to work.

**Comment by chrisglein** [comment]
The version your app is on (0.63) and the version that module is compatibile with (last update looks like it was 14 months ago, so... 0.59-ish?) won't work together. The module needs to be updated to the latest native module stuff. That's known and still pending. You can track that here: https://github.com/microsoft/react-native-windows/issues/6033
(which is in progress, yay!). Closing this issue.
