### ISSUE TITLE
Add sample that shows wrapping of a complex WinUI control from RNW

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows-samples#299]
We need a sample that shows best practices for wrapping a somewhat complex WinUI control in JS and using the same in an RNW app, exercising the ViewManager code and making the guidance for the same better.

**Comment by chrisglein** [comment]
Grouped list view would be a good choice to show a large black-box control (no RN hosted content within the list).

**Comment by harinikmsft** [comment]
I won't be able to get to this now, moving to backlog until we have the next milestone up.

**Comment by chrisglein** [comment]
Duplicate of #301
