### ISSUE TITLE
Registering your Native Module code example out of date

### ISSUE THREAD

**Issue by ryfow** [microsoft/react-native-windows-samples#300]
The C Sharp example in the "Registering Your Native Module" section of the docs is out of date. I'm not sure what you're using as an html editor, so I'm creating a bug instead of a PR.

https://microsoft.github.io/react-native-windows/docs/native-modules#2-registering-your-native-module

It needs to look like the NativeModuleSample code in order for things to compile.

```
using Microsoft.ReactNative;
using Microsoft.ReactNative.Managed;

namespace NativeModuleSample
{
    public partial class ReactPackageProvider : IReactPackageProvider
    {
        public void CreatePackage(IReactPackageBuilder packageBuilder)
        {
            CreatePackageImplementation(packageBuilder);
        }

        /// <summary>
        /// This method is implemented by the C# code generator
        /// </summary>
        partial void CreatePackageImplementation(IReactPackageBuilder packageBuilder);
    }
}
```

**Comment by dannyvv** [comment]
@jonthysell : I had actually updated the samples when updating the docs, but you asked me to revert the samples. Do you remember why and if that is still valid?

**Comment by dannyvv** [comment]
The samples now have the right code changed in PR #209
