### ISSUE TITLE
Document RootNamespace requirements in module vcxproj files

### ISSUE THREAD

**Issue by bzoz** [microsoft/react-native-windows-samples#314]
When creating a native module, the `RootNamespace` property of the project must match the namespace used in the native module. Otherwise, the project will fail to build. This is currently not documented.

Those will not match when following the getting started guide: when creating the module project `MyLibrary` is suggested as its name, whereas the sample code uses `NativeModuleSample` as its namespace.

**Comment by asklar** [comment]
@bzoz is this the same error you were seeing with #315? If so, can you check if the docs for 0.64 will be enough?
https://microsoft.github.io/react-native-windows/docs/next/native-code#compile-error-xamlmetadataprovider-is-not-a-member-of-winrtmymodulename

**Comment by bzoz** [comment]
@asklar No, it's a different error:
```
[...]\MyLibraryCPP\ReactPackageProvider.h(3,10): fatal error C1083: Cannot open include file: 'ReactPackageProvider.g.h': No such file or directory (compiling source file ReactPackageProvider.cpp)
```
The lib source I'm building [is here](https://github.com/bzoz/rnw-ui-module/tree/f79e447cd6f7a5230c0b9aa8e225fe110d80d2c8). Making [this change to the `RootNamespace`](https://github.com/bzoz/rnw-ui-module/commit/3f55c454843438f5cd9c1d34f616b90fe26a68cd) fixes the build.

I think the main issue here is that the getting started docs suggest creating `MyLibrary` as the solution name and `NativeModuleSample` as the namespace in FancyMath which doesn't work.

**Comment by asklar** [comment]
Thanks for clarifying @bzoz ! CC @jonthysell

**Comment by jonthysell** [comment]
Ok I see the confusion. Since the majority of the existing docs uses `NativeModuleSample` as the namespace, I will update the setup docs to use that name.
