### ISSUE TITLE
How to add custom user control using C++/WinRT

### ISSUE THREAD

**Issue by bzoz** [microsoft/react-native-windows-samples#315]
The UI module docs specify how to create a custom user control with C# but not with C++. Adding Blank User Control (C++/WinRT) item to the project does not work – the module itself will compile, but the app using such module will not build, failing with:
```
TestApp\windows\TestApp\Generated Files\XamlTypeInfo.g.cpp(695,44): error C2039: 'NativeModuleSample': is not a member of 'winrt'
```
Is there a way to add such control to the project?

**Comment by asklar** [comment]
@bzoz This will be documented when 0.64 ships, but here is the fix in the meantime: https://microsoft.github.io/react-native-windows/docs/next/native-code#compile-error-xamlmetadataprovider-is-not-a-member-of-winrtmymodulename
I also added it to the cppwinrt docs: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/troubleshooting#symptoms-and-remedies

LMK how this works!

**Comment by bzoz** [comment]
There is no `*_XamlTypeInfo.h` file anywhere in the solution. But just adding 
```
#include <winrt/NativeModuleSample.h>
```
(`NativeModuleSample` is both the namespace of the module, [this is the same code as in #314](https://github.com/bzoz/rnw-ui-module)) fixes the build. I haven't gotten yet to actually using the custom control in the app, but at least it builds now.

**Comment by bzoz** [comment]
Oh, yeah - I'm using autolinking for this.
