### ISSUE TITLE
Add a C# sample

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows-samples#32]
A customer just pointed out that all samples we have in this repo are C++. We should add a simple C# one - even a copy of Calculator in C# would be fine.

**Comment by jonthysell** [comment]
Calculator is in TS. :)

**Comment by TatianaKapos** [comment]
Currently the C# samples we have are
- TodosFeed as a component.
- NativeModuleSample
- AppServiceDemo

Although the only standalone windows application is AppServiceDemo, it's complex so there's benefit having a simple C# example like Calculator.
