### ISSUE TITLE
Create a branch for 0.64 samples

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows-samples#336]
The automatic upgrade pipeline worked, but we should add this to a branch and do some quick manual validation in preparation for updating everything.

**Comment by chrisglein** [comment]
Update worked, yay. Let's have these prepped so we can push them when 0.64 goes live.

**Comment by NickGerleman** [comment]
Plan I heard was to just update samples after 0.64 release since we anticipate it to be low-effort.
