### ISSUE TITLE
Remove react-native-patched references from docs

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows-samples#337]
This was a build-time directory that we don't have in 0.64. We should remove it from docs. There is a PR out, but disagreement over the scope of what we should document.

**Comment by chrisglein** [comment]
@NickGerleman can you link the PR here?
Also, can you link the pages in the docs that would need to be updated?

**Comment by NickGerleman** [comment]
Quick fix with https://github.com/microsoft/react-native-windows-samples/commit/0613454de0cf4c8568aed690e8ab932cd3035ad7
