### ISSUE TITLE
Stop recommending a specific version of Node 12

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows-samples#339]
Node 14 is now LTS. We ask users to install a specific version of Node 12. Remove or rephrase, since we have compat with the current LTS

https://microsoft.github.io/react-native-windows/docs/next/rnw-dependencies

**Comment by chrisglein** [comment]
Also need to validate that `rnw-dependencies.ps1` is updated to not push the specific version of 12. May have already been done.
