### ISSUE TITLE
Re-add docs  and add samples for task based C# native modules

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows-samples#340]
Offline discussion was that https://github.com/microsoft/react-native-windows-samples/pull/329 was the wrong change. We updated C# native modules to support Tasks, but samples still used ReactPromise. It was thought that docs were out of date, so docs were updated to refer to the old method used by samples instead of the other way around.

**Comment by chrisglein** [comment]
@dannyvv Any appetite for update the sample, or providing a snippet of what change needs to be made so we can put this up for someone else to act on?
