### ISSUE TITLE
Update native module setup guide with versions for 0.64

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows-samples#341]
https://microsoft.github.io/react-native-windows/docs/next/native-modules-setup

Uses the right version in versioned docs. Live docs (next) refer to canary versions and an older version of React than what is used in 0.64.

**Comment by chrisglein** [comment]
Would benefit from either an automated version update or non-specific versions in the docs so we don't need to do this manually each time (see also #344)
