### ISSUE TITLE
"Using Community Native Modules" should mention autolinking

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows-samples#342]
https://microsoft.github.io/react-native-windows/docs/next/native-modules-using

Gives a whole bunch of instructions for manual linking. Doesn't mention autolinking or that workflow.

**Comment by NickGerleman** [comment]
We do have a specific autolinking page below. Might be a bit confusing to someone who hasn't heard the term before though. https://microsoft.github.io/react-native-windows/docs/next/native-modules-autolinking

**Comment by chrisglein** [comment]
Agreed, more people are likely to land at the generic "Using Community Native Modules" part and not know to click the article before. We should recommend autolinking by default.
