### ISSUE TITLE
Update GitHub Actions Examples in "Native Modules Setup"

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows-samples#343]
https://microsoft.github.io/react-native-windows/docs/next/native-modules-setup

The example shows some old versions of scripts that no longer work correctly.

**Comment by chrisglein** [comment]
Deep link to section: https://microsoft.github.io/react-native-windows/docs/next/native-modules-setup#setup-ci-continuous-integration-pipeline-for-your-module
Specifically this:
```
name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.0
```
But whole area needs a scrub.
