### ISSUE TITLE
Update versions in "NuGet Update" docs

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows-samples#344]
https://microsoft.github.io/react-native-windows/docs/next/nuget-update

Directs searching for specific 0.63 strings

**Comment by chrisglein** [comment]
Would be good to have these references generic so we don't have to manually update on each release.

**Comment by NickGerleman** [comment]
Seems like we're mostly using 0.63 as an example, so this might be fine to leave as is. @dannyvv do you think we need to update the docs you wrote for 0.64? https://microsoft.github.io/react-native-windows/docs/next/nuget-update
