### ISSUE TITLE
Update docs to use new packages.config nuget restore support

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows-samples#345]
We have docs that reference using `nuget restore` but we have migrated to adopt the newer syntax (`msbuild /restore /p:RestorePackagesConfig=true`). We should update the docs to reflect that.

**Comment by chrisglein** [comment]
@asklar Can you link the places in the docs that had this so it's easy for someone to drop in and fix it?

**Comment by asklar** [comment]
https://microsoft.github.io/react-native-windows/docs/building-rnw

that page is in our docs but it isn't linked from the sidebar, BTW

We also have a mention of setting up the nuget task in CI but I don't think that's needed now anymore:
https://microsoft.github.io/react-native-windows/docs/native-modules-setup#setup-ci-continuous-integration-pipeline-for-your-module
