### ISSUE TITLE
Update and publish Calculator app to Store

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows-samples#35]
This issue tracks the progress of taking an RNW app from test to complete app release to the store. In this case the suggested app to take to completion is the calculator app.

This app could also serve as a validation app for future releases.

**Comment by Poopooracoocoo** [comment]
It'd be great for the samples to be on the Store or available as an MSIX! :D 

hey do you know why Skype switched to Electron (but still using ReactXP) and why the Xbox app is no longer in the MS Store and isn't using MSIX (at least for the installer)?

**Comment by Poopooracoocoo** [comment]
oh and a list of who is using RNW would be pretty neat. you can see who uses RN on their site. unfortunately not even ms is using rnw much as i said above.

**Comment by chrisglein** [comment]
> oh and a list of who is using RNW would be pretty neat. you can see who uses RN on their site. unfortunately not even ms is using rnw much as i said above.

#278
