### ISSUE TITLE
The KeyboardProps documentation isn't working in the last RNW build

### ISSUE THREAD

**Issue by alexanderblackh** [microsoft/react-native-windows-samples#353]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 
2. `npx react-native info`:
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 9.06 GB / 15.92 GB
  Binaries:
    Node: 14.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    Visual Studio: 16.5.30011.22 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
    Python: 3.8.5 - C:\Python38\python.EXE
  npmPackages:
    @react-native-community/cli: ^4.13.0 => 4.13.0
    react: 16.9.0 => 16.9.0
    react-native: 0.63.0 => 0.63.0
    react-native-windows: 0.63.3 => 0.63.3
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a new project (Or use any project)
2. Use the example code found [here on the API page]( https://microsoft.github.io/react-native-windows/docs/ikeyboardprops-api)

## Expected Results
Describe what you expected to happen.

Keyboards inputs are accepted. 

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by alexanderblackh** [comment]
> Does look like this sample has issues. We'll look into updating it.

Any chance this can be done ASAP? Our product may be held up entirely without keyboard and gamepad controls.

**Comment by harinikmsft** [comment]
@alexanderblackh - you might be able to find more recent and fuller set of APIs in this [spec](https://github.com/microsoft/react-native-windows/blob/master/vnext/proposals/active/keyboard-reconcile-desktop.md) while we write up some samples and docs in the website in the coming weeks.

**Comment by alexanderblackh** [comment]
> @alexanderblackh - you might be able to find more recent and fuller set of APIs in this [spec](https://github.com/microsoft/react-native-windows/blob/master/vnext/proposals/active/keyboard-reconcile-desktop.md) while we write up some samples and docs in the website in the coming weeks.

Thank you but this didn't work for us. Is it possible to get some help with this?

**Comment by rectified95** [comment]
@alexanderblackh A few weeks ago, I fixed `onKeyDown` not working for \<View>
https://github.com/microsoft/react-native-windows/pull/7406
Let us know if this helps you, and we can close this issue.

**Comment by rectified95** [comment]
Verified this works now. Closing.

**Comment by rectified95** [comment]
@alexanderblackh I just realized that my PR was addressing a problem with Pressable - this worked for View all along - can you elaborate what exactly your problem was? I am able to hit breakpoints in the keyDown handler, using the code from the website you linked to.
