### ISSUE TITLE
Update versions page to clarify release process

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows-samples#36]
The [versions page](https://microsoft.github.io/react-native-windows/versions) on the website needs to have more information around the three different types of releases we're considering making standard:

- Daily
- Preview
- Release

Each version has different sets of expectations and criteria that must to be met in order to meet the qualification necessary to climb it's way to release - it's important that we have those details publicly available on our website so our consumers and customers know what to expect when deciding which release to work from.

**Comment by jonthysell** [comment]
Our current link out to this kind of information (out of date in the 60 stable branch) is on the hanging releases page. https://github.com/microsoft/react-native-windows-samples/issues/59

**Comment by harinikmsft** [comment]
This is now captured in [releases](https://microsoft.github.io/react-native-windows/docs/releases)
