### ISSUE TITLE
Redux persist on windows app

### ISSUE THREAD

**Issue by Omar-Belghaouti** [microsoft/react-native-windows-samples#364]
Hello, I am trying to implement redux persist on a windows app, redux was working fine but once I implement the redux persist there were errors. I would like to see a sample for implementing redux persist with specifying what engine should I use.

**Comment by asklar** [comment]
You'll probably want to check out the redux persist repo if you haven't yet: https://github.com/rt2zz/redux-persist

**Comment by Omar-Belghaouti** [comment]
> You'll probably want to check out the redux persist repo if you haven't yet: https://github.com/rt2zz/redux-persist

I already did and there is no hint on using it on Windows app, I don't where is the problem but I think that the storage engine has major factor here.

**Comment by asklar** [comment]
thanks for confirming. I'm not familiar with this module but it looks to be purely javascript-based, so there's no native code needed as far as I can tell. I'd recommend filing an issue on that repo, hopefully the module owners can assist.

Leaving this issue open for now in case someone else has any idea about this module.

**Comment by NickGerleman** [comment]
redux-persist has an AsyncStorage backend for use with react-native apps. That should work for react-native-windows. Please let us know if you run into any issues though.

**Comment by Omar-Belghaouti** [comment]
> redux-persist has an AsyncStorage backend for use with react-native apps. That should work for react-native-windows. Please let us know if you run into any issues though.

Thanks it worked just fine, but when I reload the app the state is not saved on the cache (I am logging the state and there is nothing), I was under the impression that it will be saved on %TEMP% folder or on some location on the hard drive. 

Also I would like to know how it will give me space for my windows app, because I worked with it on Android and it does not give me enough space (only 6 MB or so).

**Comment by asklar** [comment]
the RNW AsyncStorage API saves its content to [ApplicationData.LocalFolder](https://docs.microsoft.com/uwp/api/Windows.Storage.ApplicationData.LocalFolder?view=winrt-19041) so the data should live under `%localappdata%\Packages\<TheAppPackageFamilyName>\`

Note that if you are re-running the app with `yarn windows` or `npx react-native run-windows`, the CLI will first uninstall the installed app before re-installing the freshly built version, and uninstalling the app deletes the local data.

**Comment by Omar-Belghaouti** [comment]
> the RNW AsyncStorage API saves its content to [ApplicationData.LocalFolder](https://docs.microsoft.com/uwp/api/Windows.Storage.ApplicationData.LocalFolder?view=winrt-19041) so the data should live under `%localappdata%\Packages\<TheAppPackageFamilyName>\`
> 
> Note that if you are re-running the app with `yarn windows` or `npx react-native run-windows`, the CLI will first uninstall the installed app before re-installing the freshly built version, and uninstalling the app deletes the local data.

Thanks for the clarification, I am using ```redux-persist``` with ```@react-native-async-storage/async-storage``` as a storage engine, I hope this will help others who want to integrate it.
