### ISSUE TITLE
Complete view manager docs

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows-samples#367]
(raw notes from mtg)
- [ ] update VM docs JSX to use function instead of class component
- [x] if (auto control = view.try_as<winrt::SampleLibraryCPP::CustomUserControlCPP>
  But there's no CPP name
- [x] IViewManagerWithExportedEventTypeConstants
- [ ] how to write event handlers in VM
- [x] SetValue usage is wrong
- [x] Conversion from Brush and other xaml and winrt types #377 and https://github.com/microsoft/react-native-windows/issues/6991

**Comment by rtorr** [comment]
@asklar is there an example anywhere (or could there be one) of having a native module with view managers?

**Comment by asklar** [comment]
yes please see the docs here https://microsoft.github.io/react-native-windows/docs/view-managers

**Comment by asklar** [comment]
closing this for now as we seem to be ok here; we may need to revise for winappsdk depending on what changes we make. CC @stmoy @AgneLukoseviciute
