### ISSUE TITLE
Popup & Flyout samples!

### ISSUE THREAD

**Issue by Omar-Belghaouti** [microsoft/react-native-windows-samples#397]
Hello, it would be a great deal if you show us how to use Flyout or Popup. I am trying to use them but I don't know what to give to the target prop. Can you help us with one sample showing us how to use them?

**Comment by chrisglein** [comment]
@chiaramooney thoughts on adding these components to [React Native Gallery](https://github.com/microsoft/react-native-gallery)? It likely isn't necessary to add specific sample apps just for these and covering in gallery is enough.

**Comment by chiaramooney** [comment]
Gallery actually already has pages for both of these!
See issue: [here](https://github.com/microsoft/react-native-gallery/issues/14)
PR: [Flyout](https://github.com/microsoft/react-native-gallery/pull/72) [Popup], (https://github.com/microsoft/react-native-gallery/pull/70)

**Comment by Omar-Belghaouti** [comment]
> Gallery actually already has pages for both of these!
> See issue: [here](https://github.com/microsoft/react-native-gallery/issues/14)
> PR: [Flyout](https://github.com/microsoft/react-native-gallery/pull/72), [Popup](https://github.com/microsoft/react-native-gallery/pull/70)

@chiaramooney why use these instead of using Modal directly from react-native?

**Comment by asklar** [comment]
@Omar-Belghaouti we don't yet support Modal (I believe this is a more recent control?). Work to add it is tracked by https://github.com/microsoft/react-native-windows/issues/2989

**Comment by Omar-Belghaouti** [comment]
Thanks @asklar we'd love to use Modal so we get the real experience of the cross platform application 😉
