### ISSUE TITLE
Instructions imply you need to create a project directory

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows-samples#41]
Might be just me, but the wording here is a bit misleading:

> Remember to call this `react-native init` in the directory you want your project to live.
> `npx react-native init <project name> --version ^0.60.0`

https://microsoft.github.io/react-native-windows/docs/getting-started#install-react-native-for-windows

It does create a directory with the name <project name>. In the folder you're in, yes.

Maybe worded more clearly like this?
> Remember to call `react-native init` from the place you want your project directory to live.

**Comment by kikisaints** [comment]
Addressed in PR #42
