### ISSUE TITLE
ref.focus() api

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/react-native-windows-samples#420]
Re: https://github.com/microsoft/react-native-windows-samples/pull/376#discussion_r595429318

I saw in the react-native-windows 0.64 blog post update PR that we have a new API (`ref.focus()`) that allows us to call focus on any React component reference. Where is that API implemented? The closest PR I could find was this one (https://github.com/microsoft/react-native-windows/pull/6220/files) which implements it for Pressable. 

Asking because I'm working on focus stuff for react-native-macOS and wanted to build off of existing effort =)

**Comment by NickGerleman** [comment]
@Saadnajmi I think this will internally go to UIManager.focus(). I think this is also in core, implemented for Android at least.

**Comment by chrisglein** [comment]
There isn't anything specific to React Native for Windows here that we're aware of. If it's under-documented in core (and that seems to be the case - I couldn't find anything obvious) you'll want to [file an issue on the  core website](https://github.com/facebook/react-native-website/issues). Sorry for having you bounce around between repos so much :(

**Comment by Saadnajmi** [comment]
Thanks @NickGerleman and @chrisglein ! No worries on hopping between repos, this has been helpful. It looks like it's coming from React (not React Native) and knowing it's implemented in core is also great. I'll keep investigating myself =)
