### ISSUE TITLE
Document CLI options on the website

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows-samples#442]
We have docs for the react-native-windows-init and for autolinking, but not for the CLI itself. 
We do have a [README.md file in the CLI](https://github.com/microsoft/react-native-windows/blob/master/packages/%40react-native-windows/cli/README.md) from where to source the information.

**Comment by chrisglein** [comment]
Some of this is in the docs, but it's a subset: https://microsoft.github.io/react-native-windows/docs/getting-started#install-the-windows-extension
It'd be better to have a single comprehensive source that is shared and also machine generated.
