### ISSUE TITLE
React native popup

### ISSUE THREAD

**Issue by Arcalise08** [microsoft/react-native-windows-samples#472]
Anyone happen to have a sample of the native module Popup. I'm having issues defining the target. I use only stateless components in react, Not sure of that's the issue or not. Haven't seen a working example of the popup module in any of the samples.

**Comment by chrisglein** [comment]
There are also examples in the gallery app: https://github.com/microsoft/react-native-gallery/

Moving this issue to the samples repo as that perhaps we can link to usage examples from the documentation.

**Comment by Arcalise08** [comment]
I see! Thanks everyone. I have got it working now with just a simple useRef in a functional component. I will say I'm a little underwhelmed with it. Perhaps there's more to it, But I has assumed that a native component named "Popup" would pop a window separate from the main app view. 

I think most people coming from a react background would be better off just creating their overlays by creating the overlay views higher up the react tree then the view you're wanting to overlay.(Or wrap the entire react root to overlay the entire application). It stands to reason then that the only reason someone would want to use the Popup component is to overlay other native components.

Not at all 100% if I'm correct in saying that. We'd need some further clarification from the dev team as to what Popups use is.

**Comment by chrisglein** [comment]
> I has assumed that a native component named "Popup" would pop a window separate from the main app view.

It has more in common with the [UWP Popup](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Primitives.Popup?view=winrt-20348), rather than a tool for creating a new window. Can you see your point that the term "popup" has overloaded meanings.

**Comment by Arcalise08** [comment]
Seems rather unnecessary to me if the popup is stuck in the bounds of the application window. React can already handle popups in that way.

**Comment by asklar** [comment]
the UWP popup allows showing outside of the app window (via the [ShouldConstrainToRootBounds](https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.primitives.popup.shouldconstraintorootbounds) property). You can locally hardcode it in the RNW code to set this property (see \vnext\Microsoft.ReactNative\Views\PopupViewManager.cpp) or you can expose it as a new property, feel free to send a PR :)

**Comment by Arcalise08** [comment]
That is definitely something worth doing. I may have time to do so on the weekends. Were having to move our project from react-native for windows as it doesn't currently support react-native-svg and that is required for our project. Although I saw it was in progress on the board so hopefully any day now!
