### ISSUE TITLE
Remove "TestProject" sample

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows-samples#473]
I don't understand what the [TestProject](https://github.com/microsoft/react-native-windows-samples/tree/master/samples/TestProject) sample is supposed to capture. It looks like it might have been accidentally checked in.

**Comment by jonthysell** [comment]
@qmatteoq Did you mean for this sample to be checked in?

**Comment by chrisglein** [comment]
It sounded like it might have been an accident that it's there. Go ahead and remove and we can restore if that's in error.

**Comment by qmatteoq** [comment]
Yes, feel free to remove, it seems it has been captured by mistake. Sorry for the issue and sorry for the delay in getting back to you, I was on vacation 😊
