### ISSUE TITLE
Remove Certificates from Sample Apps

### ISSUE THREAD

**Issue by TatianaKapos** [microsoft/react-native-windows-samples#527]
The windows sample apps still have temporary certificates that need to be removed. Currently certificates are under publisher React Native Window Samples.

**Comment by chrisglein** [comment]
@chiaramooney can you link the issue for removing it from the template?
In the meantime maybe we advise people to build debug when running samples so people aren't blocked when running this the first time (after cloning and trying to run samples).
Also if there's an issue tracking what we need to have release also work here, link that. Or create one.

**Comment by chiaramooney** [comment]
Remove Cert from Template: https://github.com/microsoft/react-native-windows/issues/8202

**Comment by TatianaKapos** [comment]
The only certificates left are in **Todosfeed and AppServiceDemo**. They both don't have workflows so the only work there would be to removing the certificate and updating the project file.

@qmatteoq Are you okay with me removing both certificates? I don't have much context for both apps so wanted to check in and make sure removing them won't break anything :)
