### ISSUE TITLE
Ensure there is a sample that demonstrates mouse hover

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows-samples#541]
[This question](https://github.com/microsoft/react-native-windows/discussions/8645) comes up often. And if a question comes up often... that means we need better documentation and we need samples that capture common scenarios.

> There's a [big thread here](https://github.com/microsoft/react-native-windows/issues/2099) about an effort to make the hover states (and other mouse-centric things) more unified across all platforms. There are options to do what you want in RNW today, but they're underdocumented (for example compared to [the keyboard props](https://microsoft.github.io/react-native-windows/docs/ikeyboardprops-api)). The lack of documentation on these props is [tracked here](https://github.com/microsoft/react-native-windows-samples/issues/358).
> 
> There are some running examples in this repo, [like this](https://github.com/microsoft/react-native-windows/blob/003602b90aeda1b2a43702c6a9307c0f01010e59/packages/%40react-native-windows/tester/src/js/examples-win/Mouse/MouseExample.windows.js). But I don't see anything proper [on the samples repo](https://github.com/microsoft/react-native-windows-samples/search?q=onMouseEnter).

**Documentation**: [Known to be missing](https://github.com/microsoft/react-native-windows-samples/issues/358).

**Samples**: We could either create a new sample that focuses on mouse hover. Or we could add usage examples to an existing sample (Calculator?) as long as it didn't contort what that sample was trying to demonstrate. Or we could add it to [react-native-gallery](https://github.com/microsoft/react-native-gallery/) as a usage example of core components. Whatever we do, it needs to be discoverable and easily linkable.

**Comment by crutchcorn** [comment]
I'd be happy to build out examples and docs for `onMouseEnter` and `onMouseLeave` if that would be helpful :) 

If so, though, I'd need to know what kind of sample we'd want (there seems to be a few options).

**Comment by TatianaKapos** [comment]
@crutchcorn That would be super helpful if you have the time! I think we're still deciding what would be the best course to go with in term of MouseEvents.

@chrisglein IMO I would lean towards having a separate example app to demonstrate mouse events (Calculator is a pretty good simple app and I wouldn't want to further complicate it), especially since we may build upon mouse events in the future, having a stand-alone app means we can just add to it.

**Comment by crutchcorn** [comment]
Just wanted to double-check on this - I'm still willing/wanting to write docs but want to make sure that I'm doing work that aligns with the goal here :) 

Should it still be a docs page [`IKeyboardView`](https://microsoft.github.io/react-native-windows/docs/ikeyboardprops-api) and an example app?

**Comment by TatianaKapos** [comment]
@crutchcorn I think we're going to hold off on the example app as mouse events are in the process of being look at. 

but our current documentation is definitely lacking so anything you can/want to add there (either creating or adding to a document page) would be much appreciated and I'm sure we'll get use out of! :)

**Comment by jonthysell** [comment]
@TatianaKapos Is this still something that makes sense for 0.69 or should it be moved to 0.70?

**Comment by TatianaKapos** [comment]
@jonthysell I actually will have a PR later today to add this example to gallery, will hopefully make .69 but can be moved to .70 if needed
