### ISSUE TITLE
AppServiceDemo isn't included in the index of the samples page

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows-samples#548]
There should be a link from [here](https://github.com/microsoft/react-native-windows-samples/tree/main/samples) to [this](https://github.com/microsoft/react-native-windows-samples/tree/main/samples/AppServiceDemo), just like there are links for all the other main samples (even if they don't have CI status). This aids with discoverability of the sample (since the top-level "SAMPLES" tab of the web page links directly there.

**Comment by Jayita10** [comment]
I want to work on this issue

**Comment by Jayita10** [comment]
I think AppServiceDemo should be added [here](https://github.com/microsoft/react-native-windows-samples/blob/main/README.md) also. @chrisglein?

**Comment by jonthysell** [comment]
> I think AppServiceDemo should be added [here](https://github.com/microsoft/react-native-windows-samples/blob/main/README.md) also. @chrisglein Chris Glein FTE?

Oops, sorry, didn't see you ask this. The answers was yes, though I already did it: https://github.com/microsoft/react-native-windows-samples/commit/d0a45fde9283beb42fc926784155a9e631d87f93
