### ISSUE TITLE
Hanging page: docs/releases

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows-samples#59]
The document here is not linked to anywhere within the website:

https://microsoft.github.io/react-native-windows/docs/releases

Is it still necessary?
* If so, does a "top-level" link need to be added to the sidebar? 
    * Linked to from another page?
    * Does its contents need updating?
* If not, can it be removed?

**Comment by chrisglein** [comment]
It seems decidedly out of date, and doesn't match the more robust release strategy that @kikisaints has been helping coordinate. I say delete it immediately and then a replacement will materialize out of that process later.

**Comment by kikisaints** [comment]
ah, yes this is very out of date and shouldn't be referenced anymore. I think the versions page should host that information.

**Comment by harinikmsft** [comment]
This was resolved with the latest [releases](https://microsoft.github.io/react-native-windows/docs/releases) page added to sidebar.
