### ISSUE TITLE
Outdated documentation.

### ISSUE THREAD

**Issue by cmachaca** [microsoft/react-native-windows-samples#593]
### Page url

https://microsoft.github.io/react-native-windows/docs/view-managers

### Problem Description

Hello.
Is there a page where I can see all the documentation about the native components in windows? The documentation that exists is outdated and is not according to the version that is published.

**Comment by asklar** [comment]
@cmachaca can you clarify what part is outdated / what doesn't match what is published?

**Comment by cmachaca** [comment]
@asklar 
I'm trying to create a native component like in the example and I can't get it up. The error is due to the fact that there are methods that do not exist. The examples also do not match what is in the repository.

**Comment by asklar** [comment]
what specific methods do not exist? the documentation is correct to the best of my knowledge (it may be missing more features, but the contents we have in there are known to work). What version of RNW are you using? is this a C# or a C++ native module? what is the error you are getting?

**Comment by cmachaca** [comment]
I develop in c ++. The examples that are in the react-native-windows repository I cannot start them because there are no methods like GetValue or SetValue. I am taking other projects as an example to be able to start them.

**Comment by cmachaca** [comment]
@asklar 
I develop in c ++. The examples that are in the react-native-windows repository I cannot start them because there are no methods like GetValue or SetValue. I am taking other projects as an example to be able to start them.

**Comment by asklar** [comment]
@cmachaca I think you might be looking at the C# docs. Make sure you select C++:

![image](https://user-images.githubusercontent.com/22989529/141408610-ddaa8de0-99cc-43ae-9ae3-911b8954fc30.png)

**Comment by chrisglein** [comment]
Hope that meets your needs! Closing this issue assuming it does.
