### ISSUE TITLE
Publish guidance doc for packaging and publishing RNW app to store

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows-samples#62]
Porting from [main repo issue](https://github.com/microsoft/react-native-windows/issues/3503) and filing here for documentation. 

This can be a sister task to #35 (as part of publishing to store, can capture the steps and publish guidance).

**Comment by chrisglein** [comment]
Related #104 and #105.
May be part of the same doc or at least discoverable from that.

**Comment by chrisglein** [comment]
Troubleshooting tips would be good too (see [linked issue](https://github.com/microsoft/react-native-windows/issues/5737) about updating SDK to avoid misleading WACK errors).

**Comment by chrisglein** [comment]
Potentially useful links:
- https://docs.microsoft.com/en-us/windows/apps/
- [Distribute your packaged desktop app](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-distribute)
- [Building an MSIX package from your code](https://docs.microsoft.com/en-us/windows/msix/desktop/source-code-overview)
- [Package a desktop or UWP app in Visual Studio](https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps#:~:text=Types%20of%20app%20packages.%201%20Before%20packaging%20your,Studio%20or%20by%20installing%20the%20package%20directly.%20)
- [Create a certificate for package signing](https://docs.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing)

**Comment by chrisglein** [comment]
Some helpful information [here](https://microsoft.github.io/react-native-windows/docs/next/native-code#distribution) maybe?

**Comment by chiaramooney** [comment]
Guidance doc created for publishing First-Party Apps to MS Store in OneNote under Troubleshooting. Steps for publishing Third-Party Apps will be different than those for First-Party. Need to do additional investigation here for Third-Party publishing steps. Theoretically should be identical to UWP publishing process.
