### ISSUE TITLE
Update Samples to v0.67

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows-samples#634]
### Suggestion

Update Samples to v0.67.

### Platforms

Windows

**Comment by TatianaKapos** [comment]
**Checklist**
Can be upgraded to 67:
- [ ] Calculator
- [ ] CalculatorNuGet
- [ ] CameraDemo
- [ ] NativeModuleSample

Can't be upgraded to 67:
- AppServiceDemo
- RssReader
- TodosFeed

**Comment by kianrp** [comment]
@TatianaKapos comment says the XAML Island sample in TodosFeed is not upgradable to 67. Does it mean, support for XAML Islands is not available with 67 as of now. If so, what is the roadmap for supporting XAML Islands.
