### ISSUE TITLE
Calculator sample app does not build from Visual Studio 2019 when repo name is too long

### ISSUE THREAD

**Issue by deatough** [microsoft/react-native-windows-samples#66]
The build failed to copy the SliderMeasurementsManager.cpp to ...\react-native-windows-samples\samples\Calculator\node_modules\react-native-windows\Microsoft.ReactNative\build\x64\Debug\Microsoft.ReactNative\react-native-patched\ReactCommon\fabric\components\slider\platform\android\SliderMeasurementsManager.cpp it did successfully copy the SliderMeasurementsManager.h file, it looks like the .cpp file cause the path length to be more than 260 characters.

**Comment by deatough** [comment]
This was caused by the registry not having long filename support enabled. Is it possible to update the msbuild scripts to detect this?

**Comment by jonthysell** [comment]
This is covered by: https://microsoft.github.io/react-native-windows/docs/rnw-dependencies#install-the-development-dependencies
