### ISSUE TITLE
Unable to run the sampleProject.

### ISSUE THREAD

**Issue by VarunTwri** [microsoft/react-native-windows-samples#686]
### Sample

NativeModuleSample

### Problem Description

Unable to run sample application:
![image](https://user-images.githubusercontent.com/102298041/164183358-dd898fd7-49ff-4618-8886-fb12ff8d876d.png)

### Steps To Reproduce

1. Clone the Project.
2. hen, within either the cppwinrt or csharp folder, install the module's dependencies. If you have yarn installed:
npm install
3.npx react-native run-windows --no-deploy --no-launch --no-packager --no-autolink

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by jonthysell** [comment]
@TatianaKapos Can you see if the NativeModule C# sample can still be built with the instructions in it's readme?

**Comment by TatianaKapos** [comment]
@jonthysell I'm not able to replicate this issue on my machine, seems to be running fine for me with both yarn/npm install.

![image](https://user-images.githubusercontent.com/42554868/165156920-19e3fbeb-98b2-493a-9508-92d4702ee48d.png)

**Comment by TatianaKapos** [comment]
@jonthysell 
Mine was building fine but after deleting/recloning the repository I was able to replicate at least some of the issue. It's building the solution but still can't find the project file.

![image](https://user-images.githubusercontent.com/42554868/165158190-9b909894-81a1-4ea7-a99a-747896090a31.png)

Work around is to run `npx react-native run-windows --no-deploy --no-launch --no-packager --no-autolink --proj "NativeModuleSample\NativeModuleSample.csproj"` but we should add this to the documentation or fix it

**Comment by TatianaKapos** [comment]
@VarunTwri does running `npx react-native run-windows --no-deploy --no-launch --no-packager --no-autolink --proj "NativeModuleSample\NativeModuleSample.csproj"` fix your build for the C# sample?

**Comment by VarunTwri** [comment]
@TatianaKapos , no mam 
getting below error
![image](https://user-images.githubusercontent.com/102298041/165672167-f5ddeb90-5e5e-43f6-82a0-8082a65221cf.png)

**Comment by TatianaKapos** [comment]
@VarunTwri Would you mind rerunning the command with the --logging flag ad sharing the error? thanks!

**Comment by VarunTwri** [comment]
8>D:\LatestSAmple\react-native-windows-samples\samples\NativeModuleSample\csharp\node_modules\react-native-windows\Microsoft.ReactNative\build\x64\Debug\Microso
       ft.ReactNative\Generated Files\winrt\Windows.ApplicationModel.Activation.h(10,10): fatal error C1083: Cannot open include file: 'winrt/impl/Windows.Applicatio 
       nModel.Appointments.AppointmentsProvider.2.h': No such file or directory (compiling source file D:\LatestSAmple\react-native-windows-samples\samples\NativeMod 
       uleSample\csharp\node_modules\react-native-windows\Shared\DevSupportManager.cpp) [D:\LatestSAmple\react-native-windows-samples\samples\NativeModuleSample\csha 
       rp\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj]
     8>D:\LatestSAmple\react-native-windows-samples\samples\NativeModuleSample\csharp\node_modules\react-native-windows\Microsoft.ReactNative\build\x64\Debug\Microso
       ft.ReactNative\Generated Files\winrt\Windows.ApplicationModel.Activation.h(10,10): fatal error C1083: Cannot open include file: 'winrt/impl/Windows.Applicatio 
       nModel.Appointments.AppointmentsProvider.2.h': No such file or directory (compiling source file ReactApplication.cpp) [D:\LatestSAmple\react-native-windows-sa 
       mples\samples\NativeModuleSample\csharp\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj]
     8>C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(486,5): error MSB4181: The "CompileXaml" task re
       turned false but did not log an error. [D:\LatestSAmple\react-native-windows-samples\samples\NativeModuleSample\csharp\node_modules\react-native-windows\Micro 
       soft.ReactNative\Microsoft.ReactNative.vcxproj]
     8>Done Building Project "D:\LatestSAmple\react-native-windows-samples\samples\NativeModuleSample\csharp\node_modules\react-native-windows\Microsoft.ReactNative\ 
       Microsoft.ReactNative.vcxproj" (default targets) -- FAILED.
     1>Done Building Project "D:\LatestSAmple\react-native-windows-samples\samples\NativeModuleSample\csharp\windows\NativeModuleSample.sln" (default targets) -- FAI 
       LED.

**Comment by VarunTwri** [comment]
@TatianaKapos  
![image](https://user-images.githubusercontent.com/102298041/166224942-58257468-5056-4c0e-81d3-5d5773a9ea95.png)

**Comment by TatianaKapos** [comment]
@VarunTwri It looks like you might be missing some dependencies, are you able to run the [dependency script](https://microsoft.github.io/react-native-windows/docs/rnw-dependencies) as well as `npx react-native info`?

**Comment by VarunTwri** [comment]
@TatianaKapos , Yes i am able to run dependency script.

while running npx react-native info, getting below:
![image](https://user-images.githubusercontent.com/102298041/166402761-e1904c66-da9a-4548-8fea-2cdb9bbc35a5.png)

**Comment by TatianaKapos** [comment]
@VarunTwri Sorry should have specified, can you run `npx react-native info` from the NativeModuleSample/csharp folder? and did the dependency script come up with all green checkmarks? thanks! :)

**Comment by VarunTwri** [comment]
@TatianaKapos 
![image](https://user-images.githubusercontent.com/102298041/167541121-59f07a17-9d6f-4651-9e62-73405dd77172.png)

**Comment by AdamCiuris** [comment]
I was able to fix this by moving the project onto the drive my OS was installed on and turning off my windows antivirus which turned itself back on.
