### ISSUE TITLE
Will React Native for macOS run on 10.12

### ISSUE THREAD

**Issue by elmcapp** [microsoft/react-native-windows-samples#710]
### Page url

https://microsoft.github.io/react-native-windows/docs/0.64/rnm-dependencies

### Problem Description

The docs say that the system requirements is macOS 10.13.   I just did a little testing and wanted to know what's prevent using React Native for macOS on version 10.12 

I bring this up as the documents may be incorrect if it can run on 10.12

**Comment by Saadnajmi** [comment]
As a rule, we generally only support N-2 releases of macOS for whatever our latest React Native macOS release is. So if React Native macOS version 0.64 was released when the latest macOS release was 10.15, we will support 10.15, 10.14, and 10.13. 

We follow this rule to ensure we're using the latest Apple API's, and remove usage of deprecated API's. On new OS releases, Apple will frequently introduce new API's, and deprecate older ones. We wanted to come up with a way to keep up to date with the changing APIS, while still supporting as many users as possible. As such, we came up with the N-2 rule. Hope that helps =)
