### ISSUE TITLE
Build fails with a long path

### ISSUE THREAD

**Issue by sameer-primelab** [microsoft/react-native-windows-samples#733]
### Sample

NativeModuleSample

### Problem Description

I am receiving this error for a missing Windows.ApplicationModel.Appointments.AppointmentsProvider.2.h
Has anyone encountered it ? 

`PS C:\project\react-native-windows-samples-main\samples\NativeModuleSample\csharp> npx react-native run-windows --no-deploy --no-launch --no-packager --no-autolink --proj "NativeModuleSample\NativeModuleSample.vsproj"
 MSBuild version 17.3.1+2badb37d1 for .NET Framework
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 10/5/2022 3:51:18 PM.
Project "C:\project\react-native-windows-samples-main\samples\NativeModuleSample\csharp\windows\NativeModuleSample.sln" on node 1 (Restore target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|x64".
_GetAllRestoreProjectPathItems:
  Determining projects to restore...
Restore:
  X.509 certificate chain validation will use the default trust store selected by .NET.
Done Building Project "C:\project\react-native-windows-samples-main\samples\NativeModuleSample\csharp\windows\NativeModuleSample.sln" (Restore target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.50
√ Restoring NuGet packages
 i Autolink step is skipped
 √ Found Solution: C:\project\react-native-windows-samples-main\samples\NativeModuleSample\csharp\windows\NativeModuleSample.sln
 i Build configuration: Debug
 i Build platform: x64
 × Building Solution: Microsoft.ReactNative.Managed.CodeGen -> C:\project\react-native-windows-samples-main\sampl...
 × Build failed with message C:\project\react-native-windows-samples-main\samples\NativeModuleSample\csharp\node_modules\react-native-windows\Microsoft.ReactNative\build\x64\Debug\Microsoft.ReactNative\Generated Files\winrt\Windows.ApplicationModel.Activation.h(10,10): fatal  error C1083: Cannot open include file: 'winrt/impl/Windows.ApplicationModel.Appointments.AppointmentsProvider.2.h': No such file or directory (compiling source file CoreApp.cpp) [C:\project\react-native-windows-samples-main\samples\NativeModuleSample\csharp\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj]. Check your build configuration.
Command failed. Re-run the command with --logging for more information.`

My OS: Windows 10 version 21H1 Build(19043.2006)

### Steps To Reproduce

1. download https://github.com/microsoft/react-native-windows-samples/tree/main/samples/NativeModuleSample
2. from command prompt go to the samples/NativeModuleSample directory
3. run _npm install_ it works
4. run npx react-native run-windows --no-deploy --no-launch --no-packager --no-autolink --proj "NativeModuleSample\NativeModuleSample.vsproj" 
it throws the said error then.

### CLI version

9.1.3

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 4.93 GB / 11.89 GB
  Binaries:
    Node: 18.9.0 - C:\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.1 - C:\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 31, 32
      Build Tools: 30.0.3, 31.0.0
      System Images: android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
      Android NDK: 22.1.7171670
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32901.82 (Visual Studio Community 2019)
  Languages:
    Java: 11.0.16.1 - C:\Program Files\Eclipse Adoptium\jdk-11.0.16.101-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.0 => 0.70.0
    react-native-windows: 0.70.2 => 0.70.2
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.70.2 is now available (your project is running on v0.70.0).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.70.2
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.70.0
info To upgrade, run "react-native upgrade".
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

**Comment by sameer-primelab** [comment]
@asklar Thank you for your quick reply.
However the error is still there with long paths turned on.
I dont really have that file winrt/impl/Windows.ApplicationModel.Appointments.AppointmentsProvider.2.h
however the winrt/impl/Windows.ApplicationModel.Appointments.AppointmentsProvider.h file is present in build directory after I run that command

`PS E:\projects\windows\react-native-windows-samples\samples\NativeModuleSample\csharp> Set-ExecutionPolicy Unrestricted -Scope Process -Force;
>> iex (New-Object System.Net.WebClient).DownloadString('https://aka.ms/rnw-deps.ps1')
Checking Free space on C: > 15 GB                            OK
Checking Installed memory >= 16 GB                Failed (warn)
Checking Windows version > 10.0.16299.0                      OK
Checking Developer mode is on                                OK
Checking Long path support is enabled                        OK
Checking Choco                                               OK
Checking git                                                 OK
Checking Compilers, build tools, SDKs and Visual Studio      OK
Checking NodeJS LTS                                          OK
Checking Chrome                                              OK
Checking Yarn                                                OK
Checking .net core 3.1                                       OK
All mandatory requirements met`

**Comment by asklar** [comment]
Ok, can you put the root of the repo higher up (e.g. `E:\rnws\...` instead of under `E:\projects\windows\react-native-windows-samples`)?
You may have to clean the build output first to get the tooling to generate some of the files that weren't generated due to long paths. To do this either open your project in Visual Studio, click on Build->Clean, or simply re-clone the repo higher up in the drive.

**Comment by sameer-primelab** [comment]
@asklar I confirm that reducing path length makes it work.
Thank you very much for your time.
