### ISSUE TITLE
Add link to RN core support policy to RNW support policy doc

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows-samples#734]
### Page url

https://microsoft.github.io/react-native-windows/support

### Problem Description

RN has their new support policy doc here: https://github.com/reactwg/react-native-releases

We should link to it within our policy doc.

**Comment by TatianaKapos** [comment]
Linking the source page: https://github.com/microsoft/react-native-windows-samples/blob/main/website/pages/en/support.js
