### ISSUE TITLE
AppServiceDemo with Hermes does not build on release

### ISSUE THREAD

**Issue by tero-paananen** [microsoft/react-native-windows-samples#776]
### Sample

AppServiceDemo

### Problem Description

Example cannot be build on release after enabling Hermes in ExperimentalFeatures.props `<UseHermes>true</UseHermes>` 

Hermes build `hermes.exe -emit-binary...`  is done two times: first with `appservicedemo` and then with the package `appservicedemo.Package`  when it try to build already builded hermes bundle and fails.

```
11>Running [C:\Users\tepaa\.nuget\packages\reactnative.hermes.windows\0.10.0-ms.1\tools\native\release\x86\hermes.exe -emit-binary -out C:\Users\tepaa\react-native-windows-samples\samples\AppServiceDemo\windows\appservicedemo\Bundle\index.windows.bundle.hbc C:\Users\tepaa\react-native-windows-samples\samples\AppServiceDemo\windows\appservicedemo\Bundle\index.windows.bundle -O -output-source-map] to precompile bundle file.
11>C:\Users\tepaa\react-native-windows-samples\samples\AppServiceDemo\windows\appservicedemo\Bundle\index.windows.bundle(1,1): error GDD431E74: Invalid UTF-8 continuation byte
11>´┐¢´┐¢´┐¢T
11>C:\Users\tepaa\react-native-windows-samples\samples\AppServiceDemo\windows\appservicedemo\Bundle\index.windows.bundle(1,1): error G1B32B4F5: unrecognized Unicode character \ufffd
11>´┐¢´┐¢´┐¢T
```

### Steps To Reproduce

1. enable hermes
2. try release build

### CLI version

6.0.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 19.83 GB / 31.90 GB
  Binaries:
    Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.31829.152 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.1 => 0.67.1
    react-native-windows: 0.67.3 => 0.67.3
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

None

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Release

**Comment by tero-paananen** [comment]
Workaround that i found is add `ContinueOnError="true"` attribute for `Exec` and two `Move` here:


https://github.com/microsoft/react-native-windows/blob/e539adbf420cf18f03070ad00cd3137dfbfab850/vnext/PropertySheets/Bundle.Common.targets#L22

to get second Hermes build by package project to continue without stopping into error.

**Comment by chrisglein** [comment]
Here's the link to the sample: https://github.com/microsoft/react-native-windows-samples/tree/main/samples/AppServiceDemo
That sample isn't particularly about using Hermes, and is locked on an older version (0.67) to match the article that went with it. I don't know if it's exactly a goal to have it durable to a change in JS engine. Version 0.67 is outside the [support window](https://microsoft.github.io/react-native-windows/support), but furthermore was before Hermes was in general support for RNW. I think it'd be more interesting to update the app and _then_ adopt Hermes. @tero-paananen have you tried updating it?

@vmoroz indicated there may have been some recent changes about how Hermes is hooked up. If there's something to add here, weigh in.

**Comment by tero-paananen** [comment]
We have this same problem in our app and workaround to get Hermes release build done is this same. Our app is solution package that contains RNW C# app and Win32 console Exe (fulltrust).

```
"react": "18.1.0",
"react-native": "0.70.6",
"react-native-windows": "0.70.10",
```

**Comment by chrisglein** [comment]
> We have this same problem in our app and workaround to get Hermes release build done is this same. Our app is solution package (.wapproj) that contains RNW C# app project (.csproj) and Win32 console Exe project (.csproj) .

Okay, so you're saying this is a general purpose build problem, not something specific to this app.

> error GDD431E74: Invalid UTF-8 continuation byte
> error G1B32B4F5: unrecognized Unicode character \ufffd

Is there a mix of encoding in your JS files? Something that's not UTF-8?

**Comment by jonthysell** [comment]
FYI, I'm updating AppServiceDemo to RNW 0.71 here: https://github.com/microsoft/react-native-windows-samples/pull/826

I didn't explicitly try building it with Hermes, but I did fix some issues in the build files during the upgrade to make sure the wapproj could still build properly.

**Comment by tero-paananen** [comment]
There is still that same Hermes build issue and maybe new issue with RELEASE/x64 build of the example. I managed to build and run on example only without Hermes on DEBUG/x64. @chrisglein
