### ISSUE TITLE
Publish getting started for mac

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows-samples#78]

**Comment by kikisaints** [comment]
do we expect this getting started guide for mac to start at version 0.62? If so, @jonthysell can we create a version folder for just one ahead of the version we're on so we can stage new site content before official release?

**Comment by harinikmsft** [comment]
If I can get this done in the next couple of days, it will start with version 0.60.0 (which is the current Mac version). It is probably a good idea to have a "next" version staged as part of the process though.
