### ISSUE TITLE
Deprecate the rssreader sample

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows-samples#793]
### Sample

RssReader

### Problem Description

The RSS Reader sample hasn't been updated since 0.62. It just triggers unnecessary dependabot PRs and has a failing CI.

### Steps To Reproduce

N/A

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Target Platform Version

None

### Visual Studio Version

None

### Build Configuration

None

**Comment by chrisglein** [comment]
Here's the link: https://github.com/microsoft/react-native-windows-samples/tree/main/samples/rssreader

Need to evaluate if the sample was providing anything particularly novel. If not, deprecate it. If so, update it.

**Comment by Saadnajmi** [comment]
Chiming in from the void, I think the "value" this had (for when I was introduced to it) was a cross-desktop app on both macOS and windows. That being said, I didn't realize the code was still kicking around.

**Comment by TatianaKapos** [comment]
I think it's still valuable to have a cross-desktop app on macOS and windows, I'll see if updating the sample is non-trivial :)

**Comment by Saadnajmi** [comment]
@TatianaKapos I plan to update it because I might want to use it for a demo coming up actually. If moved to use [React Native Test App](https://github.com/microsoft/react-native-test-app), I imagine keeping the demo (and others) up to date should be fairly easy. I'm not sure we can commit a person to maintain this sample, so I'm also completely fine with just forking the code myself for my purposes if we'd rather not maintain it here.

**Comment by jonthysell** [comment]
@Saadnajmi I'm currently refactoring the workflows in this repo: https://github.com/microsoft/react-native-windows-samples/pull/802

I'm not including rssreader in the refactor (since it doesn't build), but it shouldn't be hard to add if you're going to update rssreader soon.

Otherwise, it might make sense to just move it into samples-old.

**Comment by Saadnajmi** [comment]
I think moving to samples-old is fine. Didn't realize that existed. I can move it back out once it's updated.
