### ISSUE TITLE
C# Example issues

### ISSUE THREAD

**Issue by andreleon** [microsoft/react-native-windows-samples#85]
Hi everybody,

I cannot seem to get the C# example to run. I keep running into these errors:

<img width="549" alt="Screenshot 2020-05-01 at 17 45 31" src="https://user-images.githubusercontent.com/1391492/80818509-96a55780-8bd3-11ea-9f6a-1ad70a5ab068.png">

```
The type or namespace name 'IReactPackageProvider' could not be found (are you missing a using directive or an assembly reference?)

```
```
The type or namespace name 'IReactPackageBuilder' could not be found (are you missing a using directive or an assembly reference?) 
```

I can't figure out what is wrong, my references to Microsoft.ReactNative are in tact, in fact when I look for the IReactPackageProvider and IReactPackageBuilder it seems to all be there.

<img width="236" alt="Screenshot 2020-05-01 at 17 42 05" src="https://user-images.githubusercontent.com/1391492/80818319-3a423800-8bd3-11ea-91b9-e04949228d5e.png">

What am I doing wrong?

Thanks!

**Comment by jonthysell** [comment]
How are you consuming/building the project?

I can clone the repo, run `yarn` in the `samples\NativeModuleSample\csharp` folder, and everything builds fine in VS 2019.

**Comment by putrasurya** [comment]
anyone know how to fix this? same thing happen to me

**Comment by harinikmsft** [comment]
Hi @putrasurya - can you share more info on your environment and steps for reproducing?

**Comment by RedZepplin** [comment]
> Hi everybody,
> 
> I cannot seem to get the C# example to run. I keep running into these errors:
> 
> <img alt="Screenshot 2020-05-01 at 17 45 31" width="549" src="https://user-images.githubusercontent.com/1391492/80818509-96a55780-8bd3-11ea-9f6a-1ad70a5ab068.png">
> 
> ```
> The type or namespace name 'IReactPackageProvider' could not be found (are you missing a using directive or an assembly reference?)
> ```
> 
> ```
> The type or namespace name 'IReactPackageBuilder' could not be found (are you missing a using directive or an assembly reference?) 
> ```
> 
> I can't figure out what is wrong, my references to Microsoft.ReactNative are in tact, in fact when I look for the IReactPackageProvider and IReactPackageBuilder it seems to all be there.
> 
> <img alt="Screenshot 2020-05-01 at 17 42 05" width="236" src="https://user-images.githubusercontent.com/1391492/80818319-3a423800-8bd3-11ea-91b9-e04949228d5e.png">
> 
> What am I doing wrong?
> 
> Thanks!

Did anyone ever come up with a solution to this?

**Comment by chrisglein** [comment]
@RedZepplin Do you have more information? The last case where we were given a repo to try to repro we were unable to. At the very least we'd need basic environment information.

> 1. `npx react-native --version`:
> 2. `npx react-native info`:

Best way to do that is with a new clean bug specific to you.

**Comment by JerryMacedoCastro** [comment]
Hello. 

I was having the same problem. 

It was solved after I changed the solution platform from 'ARM' to 'x64'. 

![image](https://user-images.githubusercontent.com/39466788/111052763-ac62ea80-843c-11eb-88f7-0df10b560692.png)
