### ISSUE TITLE
Issues with Calculator sample, has not been registered

### ISSUE THREAD

**Issue by kylinholmes** [microsoft/react-native-windows-samples#910]
### Sample

Calculator

### Problem Description

When I run `npx react-native run-windows`, an error happens.

![image](https://github.com/microsoft/react-native-windows-samples/assets/45586871/89cbce1e-1c0c-4ae2-817d-216731e93861)

### Steps To Reproduce

I fllowed the readme.md in `samples/Calculator/README.md`
If there is any step didn`t write on readme?

![image](https://github.com/microsoft/react-native-windows-samples/assets/45586871/29134b0f-4c8a-4e94-8b1a-1a6e6739e747)

```bash
cd samples\Calculator\cppwinrt
yarn install
npx react-native run-windows
```

### CLI version

12.1.1

### Environment

```markdown
System:
  OS: Windows 10 10.0.19045
  CPU: "(16) x64 AMD Ryzen 7 3700X 8-Core Processor             "
  Memory: 29.92 GB / 47.93 GB
Binaries:
  Node:
    version: 18.17.1
    path: D:\SCOOP\apps\nodejs-lts\current\node.EXE
  Yarn:
    version: 1.22.19
    path: D:\SCOOP\apps\yarn\current\bin\yarn.CMD
  npm:
    version: 9.6.7
    path: D:\SCOOP\apps\nodejs-lts\current\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.17763.0
      - 10.0.19041.0
      - 10.0.20348.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.9.34414.90 (Visual Studio Community 2022)
Languages:
  Java:
    version: 17.0.9
    path: C:\Program Files\Microsoft\jdk-17.0.9.8-hotspot\bin\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.0
    wanted: 0.73.0
  react-native-windows:
    installed: 0.73.2
    wanted: 0.73.2
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by chrisglein** [comment]
These were updated to 0.73 with this PR: https://github.com/microsoft/react-native-windows-samples/pull/906
That would have been verified in an automated fashion but I'm not sure if all were manually verified. @YajurG can you check?

@kylinholmes Curious what the other error was (this shows error 2 of 2, what was 1 of 2?)

**Comment by kylinholmes** [comment]
@YajurG I clone the lastest version last week. And it seems the lastest one.
I tried to pull, and it says "Already up to date.", git log as following
![image](https://github.com/microsoft/react-native-windows-samples/assets/45586871/46ba23a8-8f68-46a1-929a-6a9d4b11de13)

**Comment by YajurG24** [comment]
That's strange -  it looks like you are up to date as I have the same output when running git log. When installing dev dependencies, did you run the script here: https://microsoft.github.io/react-native-windows/docs/rnw-dependencies

**Comment by Yajur-Grover** [comment]
Are you still facing this issue on react-native-windows v0.73.4?

**Comment by kylinholmes** [comment]
I don't know what's happen. But it's finally solved.
