### ISSUE TITLE
Need documentation for how to change JavaScript engine (e.g. Hermes or V8)

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows-samples#92]
We need instructions that capture how to apply `USE_HERMES`/`USE_V8` and such. Especially because those instructions are evolving (e.g. [see this](https://github.com/microsoft/react-native-windows/pull/4820))

**Comment by chrisglein** [comment]
Also of note, not available for UWP yet. But... will be.
In the meantime maybe a page that describes the plan and what's happening? (because people ask)

**Comment by NickGerleman** [comment]
Instructions for using Hermes on Windows/macOS available here https://github.com/microsoft/react-native-windows-samples/blob/master/docs/hermes.md
