### ISSUE TITLE
New website publishes are not refreshing the actual website

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows-samples#949]
### Page url

https://microsoft.github.io/react-native-windows/support

### Problem Description

I have made changes to the support page, which were successfully published:

* My change commit: https://github.com/microsoft/react-native-windows-samples/commit/13cf16820ccab2876b790202ee649bd0051113cd
* GitHub Action result: https://github.com/microsoft/react-native-windows-samples/actions/runs/9995605441
* Correct change in the gh-pages branch of rnw repo: https://github.com/microsoft/react-native-windows/blob/gh-pages/support/index.html

However, if I go to the page in the browser, it still has the older page version. In fact, the whole website seems stuck on a version of the website published weeks ago, every commit after [this](https://github.com/microsoft/react-native-windows-samples/commit/8a2f48d5263c7727c2c169c937f395dafbcdb5f5) is in the gh-pages branch but not appearing on the site itself.

Maybe a CDN caching issue?

**Comment by chrisglein** [comment]
GitHub actions had been turned off for some reason, but this has now been addressed.
