### ISSUE TITLE
Rework parity_status.md

### ISSUE THREAD

**Issue by TatianaKapos** [microsoft/react-native-windows-samples#989]
Not necessary for this PR, but we probably want to rework this page.

_Originally posted by @chrisglein in https://github.com/microsoft/react-native-windows-samples/pull/988#discussion_r1833623142_

**Comment by chrisglein** [comment]
Actually, looks like we deprecated that page and replaced with something that points to issues on the repo: https://microsoft.github.io/react-native-windows/docs/parity-status

So, we can consider this already done, yay!
